chore: modifies the gitlab action to have more logging.

diff --git a/.github/workflows/publish-npm.yml b/.github/workflows/publish-npm.yml
--- a/.github/workflows/publish-npm.yml
+++ b/.github/workflows/publish-npm.yml
@@ -23,8 +23,11 @@ jobs:
 
       - name: Build the package
         run: npm run build
+        
+      - name: Print npm config
+        run: npm config list
 
       - name: Publish to npm
-        run: npm publish
+        run: npm publish || echo "Publish failed with status $?"
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
